### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by JkDevArg** [CodeVisors/support#106]
Please invite me to the GitHub Community Organisation.

- #### Name: Joaquin

- #### Discord Username(if exists):

:nerd_face:

**Comment by AnkushSinghGandhi** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community :tada: 

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/CodeVisors/people

Tips for practising:

Remember contributing to open source is not just about code, its about collaboration, communication and adding value
I hope that helps
