### ISSUE TITLE
Bug in Readme

### ISSUE THREAD

**Issue by ihrishix** [CodeVisors/support#186]
**Description**

The first link to raise an issue and invite to organization, doesn't trigger the github action and send an invite. It's down in the readme file about the clear instructions

**Screenshots**
![image](https://user-images.githubusercontent.com/55173065/202867404-50b52ec0-7ec5-4ed4-97dd-dcfe55f7c55e.png)

You can also join the discord community [here](https://discord.com/invite/47vQN9Z3XB)

Feel free to check out other cool repositories of CodeVisors Community [here](https://github.com/CodeVisors)

**Comment by ihrishix** [comment]
Added a Quick Fix. Please check the PR

**Comment by AnkushSinghGandhi** [comment]
Thank you for notifying fixed the issue by updating workflow version :+1:
