### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by NS007-dev** [CodeVisors/support#52]
Please invite me to the GitHub Community Organisation.

- #### Name: CodingSpecies

- #### Discord Username(if exists):

I would like to help others in open source, and also learn too.

:nerd_face:

**Comment by AnkushSinghGandhi** [comment]
@CodingSpecies you are already a member of CodeVisors :+1:

**Comment by NS007-dev** [comment]
Oh yes, sorry @AnkushSinghGandhi.
Thank you.
